const VOCABULARY = {
    "tasketh": "Assigns",
    "scope": "Capacity",
    "hath": "Has",
    "deserved": "Earned",
    "condemn": "Judge guilty",
    "lay": "Place",
    "impose": "Place upon",
    "absolve": "Forgive",
    "distress": "Great suffering",
    "anguish": "Severe pain",
    "unto": "To",
    "ye": "You (plural)",
    "lo": "Behold",
    "goeth": "Goes",
    "prodigal": "Wasteful",
    "hurt": "Harm",
    "despair": "Lose hope",
    "forgiveth": "Forgives",
    "exhortation": "Advice",
    "balm": "Healing",
    "breasts": "Hearts",
    "verily": "Truly",
    "ripe": "Ready",
    "submit": "Yield",
    "scripture": "Sacred book",
    "prolonged": "Extended",
    "hardened": "Made hard",
    "evil-livers": "Wrongdoers",
    "fairest": "Finest",
    "paired": "Matched",
    "whereat": "At which",
    "doth": "Does",
    "creep": "Tremble",
    "soften": "Become gentle",
    "wherewith": "By which",
    "guideth": "Guides",
    "sendeth": "Sends",
    "astray": "Away from the right path",
    "whence": "From where",
    "expectation": "Expectation",
    "whosoever": "Whoever",
    "putteth": "Places",
    "suffice": "Be enough",
    "bringeth": "Brings",
    "faint": "Lose courage",
    "grieve": "Feel sorrow",
    "steadfastness": "Patience",
    "steadfast": "Patient",
    "withdraw": "Take away",
    "relieve": "Ease",
    "loose": "Untie",
    "knot": "Tie",
    "saying": "Speech",
    "deemed": "Thought",
    "save": "Except",
    "glorified": "Exalted",
    "wrong-doer": "One who does wrong",
    "glad tidings": "Good news",
    "misfortune": "Bad event",
    "striketh": "Befalls",
    "rightly": "Correctly",
    "naught": "Nothing",
    "disaster": "Calamity",
    "befalleth": "Happens",
    "escaped": "Passed away",
    "exult": "Rejoice proudly",
    "loveth": "Loves",
    "prideful": "Arrogant",
    "boasters": "People who boast",
    "resurrection": "Rising after death",
    "triumphant": "Victorious",
    "illusion": "False appearance",
    "calamity": "Disaster",
    "believeth": "Believes",
    "content": "Satisfied",
    "pleasure": "Approval",
    "bondmen": "Servants",
    "drove": "Forced out",
    "forth": "Out",
    "comrade": "Companion",
    "reassurance": "Comfort",
    "descend": "Come down",
    "supported": "Helped",
    "hosts": "Armies",
    "nethermost": "Lowest",
    "uppermost": "Highest",
    "twain": "Two",
    "whispereth": "Whispers",
    "nearer": "Closer",
    "jugular": "Neck",
    "nigh": "Near",
    "concerning": "About",
    "suppliant": "One who asks humbly",
    "crieth": "Cries",
    "aright": "Correctly",
    "hast": "Have",
    "knoweth": "Knows",
    "conference": "Meeting",
    "wheresoever": "Wherever",
    "afterward": "Afterwards",
    "inform": "Tell",
    "sufficient": "Enough",
    "scorn": "Contempt",
    "disgraced": "Shamed",
    "orphan": "Child without parents",
    "wandering": "Roaming",
    "destitute": "Extremely poor",
    "enrich": "Make rich",
    "adversity": "Hardship",
    "wrath": "Anger",
    "repel": "Drive back",
    "alike": "Similar",
    "enmity": "Hostility",
    "bosom": "Close",
    "brethren": "Brothers",
    "observe": "Keep",
    "haply": "Perhaps",
    "obtain": "Receive",
    "beneficent": "Kind",
    "modestly": "Humbly",
    "foolish": "Unwise",
    "address": "Speak to",
    "enjoineth": "Commands",
    "justice": "Fairness",
    "kinsfolk": "Relatives",
    "forbiddeth": "Prohibits",
    "lewdness": "Indecency",
    "abomination": "Detestable thing",
    "wickedness": "Evil",
    "heed": "Attention",
    "indulgence": "Leniency",
    "yearn": "Long",
    "efface": "Erase",
    "overlook": "Ignore",
    "inspired": "Guided",
    "conscience": "Moral sense",
    "causeth": "Causes",
    "stunteth": "Hinders",
    "morrow": "Tomorrow",
    "ranged": "Arranged",
    "guard": "Protect",
    "changeth": "Changes",
    "willeth": "Wills",
    "defender": "Protector",
    "greed": "Selfish desire",
    "exculpate": "Free from blame",
    "whereon": "Upon which",
    "record": "Written account",
    "speaketh": "Speaks",
    "wronged": "Treated unjustly",
    "restrained": "Controlled",
    "lust": "Strong desire",
    "ravage": "Devastate",
    "conquered": "Defeated",
    "utter": "Complete",
    "wasting": "Destruction",
    "endure": "Remain firm",
    "endurance": "Perseverance",
    "thine": "Your",
    "devise": "Plan",
    "spacious": "Large",
    "stint": "Limit",
    "loseth": "Loses",
    "dispute": "Argue",
    "lest": "For fear that",
    "falter": "Lose strength",
    "depart": "Leave",
    "therein": "In that",
    "thankful": "Grateful",
    "establish": "Set up",
    "iniquity": "Injustice",
    "persevere": "Continue steadfastly",
    "befall": "Happen",
    "ordained": "Ordered",
    "hateful": "Hated",
    "affliction": "Suffering",
    "sincere": "Honest",
    "feign": "Pretend",
    "fled": "Escaped",
    "refuge": "Shelter",
    "thy": "Your",
    "plight": "Difficult situation",
    "answereth": "Answers",
    "removeth": "Removes",
    "viceroys": "Rulers",
    "reflect": "Think deeply",
    "wast": "Were",
    "lenient": "Merciful",
    "stern": "Strict",
    "fierce": "Harsh",
    "dispersed": "Scattered",
    "consult": "Seek advice",
    "resolved": "Determined",
    "decreed": "Ordered",
    "protecting": "Guarding",
    "hour": "Final Hour",
        "to-morrow": "Tomorrow",
    "avail": "Help",
    "decision": "Judgment",
    "trusting": "Trustful",
    "sustenance": "Nourishment",
    "thereof": "Of it",
    "dependeth": "Depends",
    "habitation": "Dwelling place",
    "repository": "Resting place",
    "beareth": "Carries",
    "provision": "Supply",
    "provideth": "Provides",
    "livelihood": "Means of living",
    "unbreakable": "Indestructible",
    "might": "Great power",
    "beautified": "Made attractive",
    "jest": "Mockery",
    "enlargeth": "Enlarges",
    "straiteneth": "Restricts",
    "gracious": "Kind",
    "providence": "Provision",
    "herein": "In this",
    "portents": "Signs",
    "sicken": "Become ill",
    "healeth": "Heals",
    "afflicteth": "Afflicts",
    "household": "Family",
    "store": "Supply",
    "worshippers": "Worshippers",
    "increase": "Increase",
    "ruin": "Destruction",
    "divers": "Various",
    "hues": "Colors",
    "bellies": "Stomachs",
    "receiveth": "Takes",
    "dieth": "Dies",
    "keepeth": "Keeps",
    "dismisseth": "Releases",
    "appointed": "Fixed",
    "ascertain": "Discover",
    "despaireth": "Despairs",
    "spirit": "Spirit",
    "favour": "Favor",
    "wardeth": "Wards",
    "kindly": "Kind",
    "abode": "Home",
    "hereafter": "Afterlife",
    "neglect": "Ignore",
    "corrupters": "Corrupt people",
    "bestowed": "Given",
    "wound": "Injure",
    "fatally": "Mortally",
    "plotteth": "Plots",
    "plotters": "People who plot",
    "chooseth": "Chooses",
    "associate": "Join with",
    "hence": "From here",
    "followeth": "Follows",
    "tidings": "News",
    "supreme": "Highest",
    "triumph": "Victory",
    "defend": "Protect",
    "frighten": "Scare",
    "whereof": "Of which",
    "footsteps": "Footprints",
    "whomsoever": "Whoever",
    "commandeth": "Commands",
    "filthiness": "Impurity",
    "grace": "Favor",
    "abundance": "Plenty",
    "measured": "Limited",
    "asketh": "Asks",
    "vouchsafe": "Grant",
    "vigil": "Wakefulness",
    "two-thirds": "Two out of three parts",
    "measureth": "Measures",
    "turneth": "Turns",
    "recite": "Read aloud",
    "bounty": "Generosity",
    "poor-due": "Alms",
    "goodly": "Generous",
    "loan": "Something lent",
    "whatsoever": "Whatever",
    "recompense": "Reward",
    "fain": "Gladly",
    "hirest": "Employ",
    "pilgrimages": "Journeys",
    "completest": "Complete",
    "thine": "Yours",
    "accord": "Agreement",
    "favoured": "Blessed",
    "knewest": "Knew",
    "whereby": "By which",
    "mindful": "Careful",
    "twofold": "Double",
    "jinn": "Jinn",
    "humankind": "Humanity",
    "deemed": "Considered",
        "thinketh": "Thinks",
    "aimless": "Without purpose",
    "doeth": "Does",
    "quicken": "Give life",
    "proportion": "Correspondence",
    "ornament": "Decoration",
    "subservient": "Obedient",
    "chooseth": "Chooses",
    "whoso": "Whoever",
    "followeth": "Follows",
    "reassurance": "Comfort",
    "tidings": "Glad news",
    "astray": "Away from the right path",
    "whereof": "Of which",
    "whomsoever": "Whoever",
    "commandeth": "Commands",
    "filthiness": "Moral impurity",
    "vouchsafe": "Grant",
    "vigil": "Wakefulness",
    "two-thirds": "Two out of three parts",
    "measureth": "Measures",
    "turneth": "Turns",
    "bounty": "Generosity",
    "poor-due": "Obligatory charity",
    "goodly": "Generous",
    "whatsoever": "Whatever",
    "recompense": "Reward",
    "fain": "Gladly",
    "hirest": "Employ",
    "pilgrimages": "Pilgrimages",
    "completest": "Completes",
    "thine": "Yours",
    "accord": "Agreement",
    "favoured": "Blessed",
    "knewest": "Knew",
    "whereby": "By which",
    "twofold": "Double",
    "naught": "Nothing",
    "tasketh": "Burdens",
    "didst": "Did",
    "impose": "Place upon",
    "absolve": "Free from guilt",
    "transgressors": "Those who exceed limits",
    "reclining": "Lying back",
    "sovereignty": "Supreme authority",
    "createdst": "Created",
    "doom": "Ruin",
    "strove": "Struggled",
    "ere": "Before",
    "assemblies": "Gatherings",
    "adoration": "Worship",
    "prostrate": "Lying face down in worship",
    "bewaring": "Being cautious",
    "erudite": "Highly learned",
    "similitudes": "Parables",
    "coin": "Devise",
    "grasp": "Comprehend",
    "raven-black": "Deep black",
    "groweth": "Grows",
    "prayeth": "Prays",
    "whereas": "While",
    "allege": "Claim without proof",
    "offspring": "Children",
    "patterns": "Examples",
    "ward": "Protect",
    "abundant": "Plentiful",
    "exhortation": "Urging",
    "strayeth": "Strays",
    "aright": "Correctly",
    "refuseth": "Refuses",
    "guideth": "Guides",
    "expandeth": "Expands",
    "bosom": "Chest",
    "surrender": "Submission",
    "maketh": "Makes",
    "sheer": "Steep",
    "ascent": "Upward climb",
    "layeth": "Places",
    "ignominy": "Shame",
    "assuredly": "Certainly",
    "misleadeth": "Misleads",
    "implore": "Beg earnestly",
    "forgiveth": "Forgives",
    "wrongeth": "Wrongs",
    "seeketh": "Seeks",
    "repenteth": "Repents",
    "pardoneth": "Pardons",
    "remit": "Remove",
    "abase": "Humiliate",
    "quailed": "Lost courage",
        "aught": "Anything",
    "befell": "Happened",
    "taketh": "Takes",
    "relenteth": "Shows mercy",
    "incumbent": "Obligatory",
    "monasticism": "Monastic life",
    "ordained": "Commanded",
    "observance": "Practice",
    "evil-livers": "Wrongdoers",
    "expanded": "Opened",
    "hardened": "Made insensitive",
    "woe": "Great sorrow",
    "endeared": "Made beloved",
    "lewdness": "Immorality",
    "attendeth": "Comes to",
    "saith": "Says",
    "smite": "Strike",
    "embraceth": "Encompasses",
    "prescribed": "Established",
    "comprehendest": "Encompass",
    "expendeth": "Spends",
    "offerings": "Gifts",
    "dolorous": "Painful",
    "thereto": "To that",
    "amend": "Correct",
    "addeth": "Adds",
    "adornment": "Decoration",
    "apparent": "Clearly visible",
    "veils": "Face coverings",
    "bosoms": "Chests",
    "attendants": "Servants",
    "vigour": "Strength",
    "forsaken": "Abandoned",
    "latter": "Later",
    "withdraw": "Take away",
    "despairing": "Hopeless",
    "thankless": "Ungrateful",
    "exultant": "Overjoyed",
    "boastful": "Proud",
    "suckle": "Breastfeed",
    "fearest": "Fear",
    "dilate": "Widen",
    "eased": "Relieved",
    "weighed": "Burdened",
    "entereth": "Enters",
    "emergeth": "Emerges",
    "ascendeth": "Ascends",
    "henceforth": "From now on",
    "miscreants": "Wrongdoers",
    "signal": "Clear",
    "whisperer": "One who whispers",
    "whispereth": "Whispers",
    "slumber": "Light sleep",
    "overtaketh": "Overtakes",
    "belongeth": "Belongs",
    "intercedeth": "Pleads on behalf of",
    "includeth": "Includes",
    "sublime": "Exalted",
    "tremendous": "Very great",
    "foolhardiness": "Reckless boldness",
    "descend": "Come down",
    "thereby": "By that means",
    "reckon": "Count",
    "ingrate": "Ungrateful person",
    "nigh": "Near",
    "devotion": "Dedication",
    "invisible": "Unseen",
    "sovereign": "Supreme ruler",
    "compeller": "One who compels",
    "superb": "Magnificent",
    "shaper": "One who forms",
    "fashioner": "One who designs",
    "glorifieth": "Glorifies",
    "proclaimed": "Announced publicly",
    "dire": "Extremely serious",
    "weaning": "Ending breastfeeding",
    "commended": "Instructed",
    "reluctance": "Unwillingness",
    "attaineth": "Reaches",
    "wherewith": "By which",
    "repulse": "Reject harshly",
    "announceth": "Announces",
    "therefor": "For that",
    "lovingkindness": "Loving kindness",
    "scoreth": "Earns",
    "responsive": "Answering prayers",
    "twain": "Two",
    "fables": "Stories",
    "favours": "Blessings",
    "fashioned": "Formed",
    "breathed": "Blew",
    "assigned": "Given",
    "returneth": "Returns",
    "ungrateful": "Not thankful",
        "serviceable": "Useful",
    "disputeth": "Argues",
    "majesty": "Greatness",
    "imperishable": "Lasting forever",
    "morn": "Morning",
    "township": "Small town",
    "dwelt": "Lived",
    "dearth": "Scarcity",
    "garb": "Clothing",
    "lawful": "Permissible",
    "trustees": "Caretakers",
    "disdain": "Contempt",
    "piety": "Devotion",
    "spoil": "War booty",
    "wayfarer": "Traveler",
    "commodity": "Trade item",
    "forbiddeth": "Forbids",
    "abstain": "Refrain",
    "reprisal": "Punishment",
    "wretch": "Miserable person",
    "kindlier": "More kindly",
    "soweth": "Sows",
    "discord": "Conflict",
    "foe": "Enemy",
    "tribes": "Clans",
    "noblest": "Most honorable",
    "acknowledged": "Recognized",
    "chastity": "Sexual purity",
    "attentive": "Paying close attention",
    "raiment": "Clothing",
    "vigil": "Staying awake",
    "abate": "Reduce",
    "chant": "Recite rhythmically",
    "keen": "Sharp",
    "preserveth": "Preserves",
    "lewdness": "Immorality",
    "iniquity": "Wickedness",
    "enjoined": "Commanded",
    "therefor": "Therefore",
    "ere": "Before",
    "mayst": "May",
    "vouchsafed": "Granted",
    "seer": "One who sees",
    "sendeth": "Sends",
    "reviving": "Bringing back to life",
    "ordinance": "Order",
    "obedient": "Subject",
    "helpmeets": "Spouses",
    "portents": "Signs",
    "heed": "Pay attention",
    "quickeneth": "Brings to life",
    "calleth": "Calls",
    "rifts": "Cracks",
    "weakened": "Made weak",
    "dim": "Faint",
    "manifest": "Clear",
    "suffice": "Be enough",
    "whence": "From where",
    "pasture": "Graze",
    "therewith": "With that",
    "constrained": "Subjected",
    "subservient": "Serving",
    "divers": "Various",
    "hues": "Colors",
    "scattereth": "Scatters",
    "pageantry": "Showy display",
    "rivalry": "Competition",
    "vegetation": "Plant life",
    "husbandman": "Farmer",
    "drieth": "Dries",
    "becometh": "Becomes",
    "straw": "Dried stalks",
    "grievous": "Severe",
    "pastime": "Recreation",
    "leaveth": "Leaves",
    "confronting": "Facing",
    "agony": "Intense pain",
    "wast": "Were",
    "wont": "Accustomed",
    "shun": "Avoid",
    "heedlessness": "Lack of awareness",
    "piercing": "Sharp",
    "endeavour": "Effort",
    "stand forth": "Appear clearly",
    "seeth": "Sees",
    "preferred": "Favored",
    "encloseth": "Encloses",
    "showers": "Scalding liquid",
    "molten": "Melted",
    "burneth": "Burns",
    "calamitous": "Terrible",
    "resting-place": "Place of rest",
    "ponder": "Think deeply",
    "meditate": "Reflect deeply",
    "incongruity": "Inconsistency",
    "remembereth": "Remembers",
    "haply": "Perhaps",
    "peradventure": "Perhaps",
    "mine": "My",
    "coined": "Presented",
    "similitudes": "Comparisons",
};